-- CONEXIÓN DOMICILIOS PANEL <-> INDEX
-- Ejecutar después de panel_arreglos.sql y panel_domicilios_dos_puntos.sql.

create table if not exists public.configuracion_ciudades_domicilios (
  id bigint generated by default as identity primary key,
  ciudad text not null unique,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

alter table public.configuracion_ciudades_domicilios enable row level security;

drop policy if exists "ciudades domicilio lectura publica" on public.configuracion_ciudades_domicilios;
create policy "ciudades domicilio lectura publica"
on public.configuracion_ciudades_domicilios for select
using (true);

drop policy if exists "ciudades domicilio admin inserta" on public.configuracion_ciudades_domicilios;
create policy "ciudades domicilio admin inserta"
on public.configuracion_ciudades_domicilios for insert to authenticated
with check (public.mi_rol_privado() = 'administrador');

drop policy if exists "ciudades domicilio admin actualiza" on public.configuracion_ciudades_domicilios;
create policy "ciudades domicilio admin actualiza"
on public.configuracion_ciudades_domicilios for update to authenticated
using (public.mi_rol_privado() = 'administrador')
with check (public.mi_rol_privado() = 'administrador');

drop policy if exists "ciudades domicilio admin elimina" on public.configuracion_ciudades_domicilios;
create policy "ciudades domicilio admin elimina"
on public.configuracion_ciudades_domicilios for delete to authenticated
using (public.mi_rol_privado() = 'administrador');

-- Estas son exactamente las ciudades que actualmente ofrece el index.
insert into public.configuracion_ciudades_domicilios (ciudad)
values
  ('Pereira'),
  ('Dosquebradas'),
  ('Cerritos'),
  ('Cuba'),
  ('Santa Rosa de Cabal'),
  ('Parque Industrial'),
  ('Vía Armenia')
on conflict (ciudad) do nothing;

-- Mantener sincronizadas también las ciudades que ya tengan zonas configuradas.
insert into public.configuracion_ciudades_domicilios (ciudad)
select distinct trim(ciudad)
from public.configuracion_domicilios
where trim(ciudad) <> ''
on conflict (ciudad) do nothing;

-- Las ciudades activas son públicas para que el index pueda mostrarlas.
grant select on public.configuracion_ciudades_domicilios to anon, authenticated;
