-- Configuración de domicilios + limpieza técnica para el panel.
-- Ejecutar en Supabase SQL Editor antes de usar estas nuevas funciones.

create table if not exists public.configuracion_domicilios (
  id bigint generated by default as identity primary key,
  ciudad text not null,
  zona text not null,
  precio numeric(12,2) not null default 0 check (precio >= 0),
  sucursal text not null check (sucursal in ('Cuba','Circunvalar')),
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (ciudad, zona)
);

alter table public.configuracion_domicilios enable row level security;

drop policy if exists "domicilios lectura publica" on public.configuracion_domicilios;
create policy "domicilios lectura publica"
on public.configuracion_domicilios for select
using (true);

-- El panel usa la sesión autenticada. Estas políticas delegan el permiso real
-- a la función existente mi_rol_privado().
drop policy if exists "domicilios admin inserta" on public.configuracion_domicilios;
create policy "domicilios admin inserta"
on public.configuracion_domicilios for insert to authenticated
with check (public.mi_rol_privado() = 'administrador');

drop policy if exists "domicilios admin actualiza" on public.configuracion_domicilios;
create policy "domicilios admin actualiza"
on public.configuracion_domicilios for update to authenticated
using (public.mi_rol_privado() = 'administrador')
with check (public.mi_rol_privado() = 'administrador');

drop policy if exists "domicilios admin elimina" on public.configuracion_domicilios;
create policy "domicilios admin elimina"
on public.configuracion_domicilios for delete to authenticated
using (public.mi_rol_privado() = 'administrador');

create or replace function public.borrar_recibos_domicilios_tecnico()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  total_borrados bigint := 0;
begin
  if public.mi_rol_privado() <> 'tecnico' then
    raise exception 'Solo un técnico puede borrar los recibos de domicilios.';
  end if;

  -- Primero elimina auditoría relacionada para evitar conflictos de FK.
  delete from public.historial_pedidos
  where pedido_id in (select id from public.pedidos where modalidad = 'domicilio');

  delete from public.pedidos where modalidad = 'domicilio';
  get diagnostics total_borrados = row_count;

  return total_borrados;
end;
$$;

create or replace function public.borrar_historial_pedidos_tecnico()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  total_borrados bigint;
begin
  if public.mi_rol_privado() <> 'tecnico' then
    raise exception 'Solo un técnico puede borrar el historial.';
  end if;

  delete from public.historial_pedidos;
  get diagnostics total_borrados = row_count;
  return total_borrados;
end;
$$;

revoke all on function public.borrar_recibos_domicilios_tecnico() from public;
grant execute on function public.borrar_recibos_domicilios_tecnico() to authenticated;
revoke all on function public.borrar_historial_pedidos_tecnico() from public;
grant execute on function public.borrar_historial_pedidos_tecnico() to authenticated;

-- Datos iniciales actuales del proyecto. Si ya existen, no se duplican.
insert into public.configuracion_domicilios (ciudad,zona,precio,sucursal,activo) values
('Pereira','Centro Pereira',5000,'Cuba',true),
('Pereira','Cuba',5000,'Cuba',true),
('Pereira','Circunvalar',6000,'Circunvalar',true),
('Pereira','Alamos',6000,'Circunvalar',true),
('Pereira','Cerritos',9000,'Circunvalar',true),
('Pereira','Cerritos - Zona rural',12000,'Circunvalar',true),
('Dosquebradas','Dosquebradas Centro',8000,'Cuba',true),
('Dosquebradas','Dosquebradas - La Pradera',8500,'Cuba',true),
('Dosquebradas','Dosquebradas - La Badea',9000,'Cuba',true)
on conflict (ciudad,zona) do nothing;
