-- ============================================================
-- EMPANADAS QUE RICO — SINCRONIZAR MENÚ ACTUAL
-- Este archivo deja public.productos EXACTAMENTE igual al menú
-- que tenía el index entregado con estos archivos.
--
-- IMPORTANTE: ejecútalo una vez después de ejecutar
-- supabase_integracion.sql.
-- ============================================================

create table if not exists public.productos (
  id text primary key,
  categoria text not null,
  icono text not null default '🍽️',
  nombre text not null,
  descripcion text not null default '',
  precio numeric(12,2) not null default 0,
  sucursales text[] not null default '{}',
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

-- Elimina productos antiguos que ya no pertenecen al menú actual.
delete from public.productos
where id not in (
  'papa-mixta',
  'papa-barril',
  'emp-carne',
  'emp-pollo',
  'emp-mixta',
  'emp-chicharron-platano',
  'emp-queso',
  'emp-ranchera',
  'emp-carne-barril',
  'arepa-huevo-perico-carne',
  'mega-tradicional-30',
  'mega-arrecha',
  'mega-desmechada',
  'mega-barril',
  'coca-01',
  'coca-02',
  'coca-03',
  'coca-04',
  'coca-05',
  'coca-06',
  'coca-07',
  'coca-08',
  'coca-09',
  'coca-10',
  'coca-11',
  'coca-12',
  'coca-13',
  'coca-14',
  'coca-15',
  'coca-16',
  'coca-17',
  'postobon-01',
  'postobon-02',
  'postobon-03',
  'postobon-04',
  'postobon-05',
  'postobon-06',
  'postobon-07',
  'postobon-08',
  'postobon-09',
  'postobon-10',
  'postobon-11',
  'postobon-12',
  'postobon-13',
  'postobon-14',
  'postobon-15',
  'postobon-16',
  'postobon-17',
  'postobon-18',
  'postobon-19',
  'postobon-20',
  'postobon-21',
  'postobon-22',
  'postobon-23',
  'postobon-24',
  'postobon-25',
  'cong-carne',
  'cong-pollo',
  'cong-mixta',
  'cong-queso',
  'cong-barril',
  'cong-ranchera',
  'cong-chicharron',
  'salsa-tomate',
  'salsa-ajo',
  'salsa-rosada',
  'salsa-picante',
  'salsa-tartara',
  'salsa-mostaza',
  'salsa-miel-mostaza',
  'salsa-bbq',
  'salsa-chimichurri',
  'salsa-guacamole',
  'salsa-hogao',
  'salsa-mayonesa',
  'salsa-mayonesa-ajo',
  'salsa-cilantro',
  'salsa-aguacate',
  'salsa-queso',
  'salsa-ranch',
  'salsa-maracuya',
  'salsa-pina',
  'salsa-especial'
);

insert into public.productos
(id,categoria,icono,nombre,descripcion,precio,sucursales,activo,creado_en,actualizado_en)
values
('papa-mixta','Papas rellenas','🥔','Papa Mixta','Carne, pollo y huevo cocinado.',5000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('papa-barril','Papas rellenas','🥔','Papa Rellena de Carne Asada al Barril','Papa rellena de carne asada al barril.',5000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('emp-carne','Empanadas','🥟','Empanada de carne desmechada','Carne desmechada de res y papa.',2500,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('emp-pollo','Empanadas','🥟','Empanada de pollo','Pollo y papa.',2500,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('emp-mixta','Empanadas','🥟','Empanada mixta','Pollo, carne de res y papa.',2500,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('emp-chicharron-platano','Empanadas','🥟','Empanada de chicharrón con plátano maduro','Chicharrón y plátano maduro.',3000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('emp-queso','Empanadas','🥟','Empanada de queso','Queso.',3000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('emp-ranchera','Empanadas','🥟','Empanada ranchera','Carne de res, queso, tocineta y salchicha.',4000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('emp-carne-barril','Empanadas','🥟','Empanada de carne asada al barril','Carne asada al barril.',4000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('arepa-huevo-perico-carne','Arepas','🫓','Arepa de huevo, perico y carne desmechada','Huevo, perico y carne desmechada.',6000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('mega-tradicional-30','Mega empanadas de 30 cm','🥟','Mega Empanada Tradicional de 30 cm','Carne, pollo, chicharrón, tocineta, queso, salchicha ranchera, plátano maduro y carne asada al barril.',12000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('mega-arrecha','Mega empanadas de 30 cm','🥟','Mega Arrecha','Arroz, pollo, chicharrón, tocineta, carne asada al barril, queso, plátano y salchicha ranchera.',15000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('mega-desmechada','Mega empanadas de 30 cm','🥟','Mega Desmechada','Carne de res desmechada con guiso criollo.',15000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('mega-barril','Mega empanadas de 30 cm','🥟','Mega Barril','Carne asada al barril.',15000,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('coca-01','Coca-Cola','🥤','Coca-Cola','Bebida gaseosa o refresco.',4000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-02','Coca-Cola','🥤','Ginger','Bebida gaseosa o refresco.',3000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-03','Coca-Cola','🥤','Premio','Bebida gaseosa o refresco.',3000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-04','Coca-Cola','🥤','Sun Tea','Bebida gaseosa o refresco.',4000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-05','Coca-Cola','🥤','Del Valle','Bebida gaseosa o refresco.',3000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-06','Coca-Cola','🥤','Agua','Bebida gaseosa o refresco.',3000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-07','Coca-Cola','🥤','Sprite','Bebida gaseosa o refresco.',3000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-08','Coca-Cola','🥤','Fanta','Bebida gaseosa o refresco.',3000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-09','Coca-Cola','🥤','Quatro','Bebida gaseosa o refresco.',3000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-10','Coca-Cola','🥤','Soda','Bebida gaseosa o refresco.',4000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-11','Coca-Cola','🥤','Del Valle Frutos','Bebida gaseosa o refresco.',4000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-12','Coca-Cola','🥤','Coca-Cola 1.5 L','Bebida gaseosa o refresco.',7000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-13','Coca-Cola','🥤','Sprite 1.5 L','Bebida gaseosa o refresco.',7000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-14','Coca-Cola','🥤','Coca-Cola 2.25 L','Bebida gaseosa o refresco.',9000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-15','Coca-Cola','🥤','Coca-Cola 3 L','Bebida gaseosa o refresco.',12000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-16','Coca-Cola','🥤','Del Valle 1.5 L','Bebida gaseosa o refresco.',7000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('coca-17','Coca-Cola','🥤','Quatro 1.5 L','Bebida gaseosa o refresco.',7000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('postobon-01','Postobón','🥤','Postobón Manzana 250 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-02','Postobón','🥤','Postobón Manzana 400 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-03','Postobón','🥤','Postobón Manzana 600 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-04','Postobón','🥤','Postobón Manzana 1.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-05','Postobón','🥤','Postobón Manzana 2.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-06','Postobón','🥤','Postobón Colombiana 250 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-07','Postobón','🥤','Postobón Colombiana 400 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-08','Postobón','🥤','Postobón Colombiana 600 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-09','Postobón','🥤','Postobón Colombiana 1.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-10','Postobón','🥤','Postobón Colombiana 2.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-11','Postobón','🥤','Postobón Uva 250 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-12','Postobón','🥤','Postobón Uva 400 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-13','Postobón','🥤','Postobón Uva 600 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-14','Postobón','🥤','Postobón Uva 1.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-15','Postobón','🥤','Postobón Uva 2.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-16','Postobón','🥤','Postobón Naranja 250 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-17','Postobón','🥤','Postobón Naranja 400 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-18','Postobón','🥤','Postobón Naranja 600 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-19','Postobón','🥤','Postobón Naranja 1.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-20','Postobón','🥤','Postobón Naranja 2.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-21','Postobón','🥤','Postobón Tamarindo 250 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-22','Postobón','🥤','Postobón Tamarindo 400 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-23','Postobón','🥤','Postobón Tamarindo 600 ml','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-24','Postobón','🥤','Postobón Tamarindo 1.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('postobon-25','Postobón','🥤','Postobón Tamarindo 2.5 L','Bebida gaseosa.',4000,ARRAY['Cuba']::text[],true,now(),now()),
('cong-carne','Congeladas','🧊','Empanadas congeladas de carne x12','Paquete de 12 unidades.',24000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('cong-pollo','Congeladas','🧊','Empanadas congeladas de pollo x12','Paquete de 12 unidades.',24000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('cong-mixta','Congeladas','🧊','Empanadas congeladas mixtas x12','Paquete de 12 unidades.',24000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('cong-queso','Congeladas','🧊','Empanadas congeladas de queso x12','Paquete de 12 unidades.',30000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('cong-barril','Congeladas','🧊','Empanadas congeladas de carne al barril x12','Paquete de 12 unidades.',42000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('cong-ranchera','Congeladas','🧊','Empanadas congeladas rancheras x12','Paquete de 12 unidades.',42000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('cong-chicharron','Congeladas','🧊','Empanadas congeladas de chicharrón x12','Paquete de 12 unidades.',30000,ARRAY['Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-tomate','Salsas','🧂','Salsa de tomate','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-ajo','Salsas','🧂','Salsa de ajo','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-rosada','Salsas','🧂','Salsa rosada','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-picante','Salsas','🧂','Salsa picante','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-tartara','Salsas','🧂','Salsa tártara','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-mostaza','Salsas','🧂','Salsa de mostaza','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-miel-mostaza','Salsas','🧂','Salsa miel mostaza','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-bbq','Salsas','🧂','Salsa BBQ','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-chimichurri','Salsas','🧂','Salsa chimichurri','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-guacamole','Salsas','🧂','Guacamole','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-hogao','Salsas','🧂','Salsa de hogao','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-mayonesa','Salsas','🧂','Mayonesa','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-mayonesa-ajo','Salsas','🧂','Mayonesa de ajo','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-cilantro','Salsas','🧂','Salsa de cilantro','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-aguacate','Salsas','🧂','Salsa de aguacate','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-queso','Salsas','🧂','Salsa de queso','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-ranch','Salsas','🧂','Salsa ranch','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-maracuya','Salsas','🧂','Salsa de maracuyá','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-pina','Salsas','🧂','Salsa de piña','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now()),
('salsa-especial','Salsas','🧂','Salsa especial','Salsa para acompañar.',0,ARRAY['Centro','Cuba','Circunvalar']::text[],true,now(),now())
on conflict (id) do update set
  categoria=excluded.categoria,
  icono=excluded.icono,
  nombre=excluded.nombre,
  descripcion=excluded.descripcion,
  precio=excluded.precio,
  sucursales=excluded.sucursales,
  activo=excluded.activo,
  actualizado_en=now();

notify pgrst, 'reload schema';
